services:
  db:
    image: postgres:18
    container_name: drf_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: drf_adminer
    restart: always
    ports:
      - "8080:8080"
